# Change these first
owner: andrewnyr
repo: uptime

# Add your sites here
sites:
  - name: andrewnet
    url: https://www.andrewnet.net
    icon: https://cloud.cdn.andrewnet.net/images/assets/a-circle-favicon-inverted.png
  - name: andrewnet authentication
    url: $AUTHURL
    icon: https://cloud.cdn.andrewnet.net/images/assets/a-circle-favicon-inverted.png
  - name: andrewnet cloud cdn
    url: https://cloud.cdn.andrewnet.net
    icon: https://cloud.cdn.andrewnet.net/images/assets/a-circle-favicon-inverted.png
  - name: nextcloud
    url: https://nxtc.andrewnet.net/
    icon: https://cloud.cdn.andrewnet.net/images/assets/a-circle-favicon-inverted.png
  - name: njit website
    url: https://web.njit.edu/~aja9/


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.andrewnet.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cloud.cdn.andrewnet.net/images/assets/a-circle-favicon-inverted.png
  logoHref: https://www.andrewnet.net
  favicon: https://cloud.cdn.andrewnet.net/favicon.ico
  name: Upptime
  introTitle: "the official andrewnet status page"
  introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
